# Generated by Django 4.0 on 2021-12-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0002_rename_gategory_depency_category_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='depency',
            options={'verbose_name': 'Depence'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name': 'Salaire'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(verbose_name='Salary entry date'),
        ),
    ]
