# Generated by Django 4.0 on 2021-12-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0003_alter_category_options_alter_depency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depency',
            name='votes',
        ),
    ]
