# Generated by Django 4.0 on 2022-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0006_alter_family_options_depency_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depency',
            name='date',
            field=models.TextField(default='12-02-22 16:18'),
            preserve_default=False,
        ),
    ]
