# Generated by Django 4.0 on 2022-02-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0007_depency_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depency',
            name='date',
            field=models.TextField(default='12-02-22 16:18', null=True),
        ),
    ]
